# ========================
# SERVER CONFIGURATION
# ========================
server.port=8080

# ========================
# DATASOURCE (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ========================
# JWT CONFIGURATION
# ========================
jwt.secret=dGlja2V0Ym9va2luZ3N5c3RlbXNlY3JldGtleWZvcmp3dHRva2VuMjAyNg==
jwt.expiration=86400000

# ========================
# REDIS
# ========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ========================
# APPLICATION
# ========================
spring.application.name=ticket-booking-system
